In [108]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_squared_error, r2_score
import joblib

In [4]:
dataset = pd.read_csv('Air_Data.csv')
dataset


No  year  month  day  hour   PM2  PM10   SO2   NO2     CO    O3  \
0          1  2013      3    1     0   4.0   4.0   4.0   7.0  300.0  77.0   
1          2  2013      3    1     1   8.0   8.0   4.0   7.0  300.0  77.0   
2          3  2013      3    1     2   7.0   7.0   5.0  10.0  300.0  73.0   
3          4  2013      3    1     3   6.0   6.0  11.0  11.0  300.0  72.0   
4          5  2013      3    1     4   3.0   3.0  12.0  12.0  300.0  72.0   
...      ...   ...    ...  ...   ...   ...   ...   ...   ...    ...   ...   
35059  35060  2017      2   28    19  12.0  29.0   5.0  35.0  400.0  95.0   
35060  35061  2017      2   28    20  13.0  37.0   7.0  45.0  500.0  81.0   
35061  35062  2017      2   28    21  16.0  37.0  10.0  66.0  700.0  58.0   
35062  35063  2017      2   28    22  21.0  44.0  12.0  87.0  700.0  35.0   
35063  35064  2017      2   28    23  19.0  31.0  10.0  79.0  600.0  42.0   

       TEMP    PRES  DEWP  RAIN   wd  WSPM       station  
0      -0.7  1023.0 -18.8   0.0  NNW   4.4  Aotizhongxin  
1      -1.1  1023.2 -18.2   0.0    N   4.7  Aotizhongxin  
2      -1.1  1023.5 -18.2   0.0  NNW   5.6  Aotizhongxin  
3      -1.4  1024.5 -19.4   0.0   NW   3.1  Aotizhongxin  
4      -2.0  1025.2 -19.5   0.0    N   2.0  Aotizhongxin  
...     ...     ...   ...   ...  ...   ...           ...  
35059  12.5  1013.5 -16.2   0.0   NW   2.4  Aotizhongxin  
35060  11.6  1013.6 -15.1   0.0  WNW   0.9  Aotizhongxin  
35061  10.8  1014.2 -13.3   0.0   NW   1.1  Aotizhongxin  
35062  10.5  1014.4 -12.9   0.0  NNW   1.2  Aotizhongxin  
35063   8.6  1014.1 -15.9   0.0  NNE   1.3  Aotizhongxin  

[35064 rows x 18 columns]

In [6]:
  dataset.shape


(35064, 18)

In [38]:
PM2_median = dataset.PM2.median()
PM2_median

58.0

In [39]:
dataset.PM2 = dataset.PM2.fillna(PM2_median)
dataset.PM2.isnull().sum()

0

In [40]:
PM10_median = dataset.PM10.median()
PM10_median

87.0

In [41]:
dataset.PM10 = dataset.PM10.fillna(PM10_median)
dataset.PM10.isnull().sum()

0

In [42]:
SO2_median = dataset.SO2.median()
SO2_median

9.0

In [43]:
dataset.SO2 = dataset.SO2.fillna(SO2_median)
dataset.SO2.isnull().sum()

0

In [44]:
NO2_median = dataset.NO2.median()
NO2_median

53.0

In [45]:
dataset.NO2 = dataset.NO2.fillna(NO2_median)
dataset.NO2.isnull().sum()

0

In [46]:
CO_median = dataset.CO.median()
CO_median

900.0

In [47]:
dataset.CO = dataset.CO.fillna(CO_median)
dataset.CO.isnull().sum()

0

In [48]:
O3_median = dataset.O3.median()
O3_median

42.0

In [49]:
dataset.O3 = dataset.O3.fillna(O3_median)
dataset.O3.isnull().sum()

0

In [50]:
TEMP_median = dataset.TEMP.median()
TEMP_median

14.5

In [51]:
dataset.TEMP = dataset.TEMP.fillna(TEMP_median)
dataset.TEMP.isnull().sum()

0

In [52]:
PRES_median = dataset.PRES.median()
PRES_median

1011.4

In [53]:
dataset.PRES = dataset.PRES.fillna(PRES_median)
dataset.PRES.isnull().sum()

0

In [54]:
DEWP_median = dataset.DEWP.median()
DEWP_median

3.8

In [55]:
dataset.DEWP = dataset.DEWP.fillna(DEWP_median)
dataset.DEWP.isnull().sum()

0

In [56]:
RAIN_median = dataset.RAIN.median()
RAIN_median

0.0

In [57]:
dataset.RAIN = dataset.RAIN.fillna(RAIN_median)
dataset.RAIN.isnull().sum()

0

In [58]:
WSPM_median = dataset.WSPM.median()
WSPM_median

1.4

In [59]:
dataset.WSPM = dataset.WSPM.fillna(WSPM_median)
dataset.WSPM.isnull().sum()

0

In [60]:
dataset.drop(columns=['No','wd','station'])

year  month  day  hour   PM2  PM10   SO2   NO2     CO    O3  TEMP  \
0      2013      3    1     0   4.0   4.0   4.0   7.0  300.0  77.0  -0.7   
1      2013      3    1     1   8.0   8.0   4.0   7.0  300.0  77.0  -1.1   
2      2013      3    1     2   7.0   7.0   5.0  10.0  300.0  73.0  -1.1   
3      2013      3    1     3   6.0   6.0  11.0  11.0  300.0  72.0  -1.4   
4      2013      3    1     4   3.0   3.0  12.0  12.0  300.0  72.0  -2.0   
...     ...    ...  ...   ...   ...   ...   ...   ...    ...   ...   ...   
35059  2017      2   28    19  12.0  29.0   5.0  35.0  400.0  95.0  12.5   
35060  2017      2   28    20  13.0  37.0   7.0  45.0  500.0  81.0  11.6   
35061  2017      2   28    21  16.0  37.0  10.0  66.0  700.0  58.0  10.8   
35062  2017      2   28    22  21.0  44.0  12.0  87.0  700.0  35.0  10.5   
35063  2017      2   28    23  19.0  31.0  10.0  79.0  600.0  42.0   8.6   

         PRES  DEWP  RAIN  WSPM  
0      1023.0 -18.8   0.0   4.4  
1      1023.2 -18.2   0.0   4.7  
2      1023.5 -18.2   0.0   5.6  
3      1024.5 -19.4   0.0   3.1  
4      1025.2 -19.5   0.0   2.0  
...       ...   ...   ...   ...  
35059  1013.5 -16.2   0.0   2.4  
35060  1013.6 -15.1   0.0   0.9  
35061  1014.2 -13.3   0.0   1.1  
35062  1014.4 -12.9   0.0   1.2  
35063  1014.1 -15.9   0.0   1.3  

[35064 rows x 15 columns]

In [61]:
dataset.isnull().any()

No         False
year       False
month      False
day        False
hour       False
PM2        False
PM10       False
SO2        False
NO2        False
CO         False
O3         False
TEMP       False
PRES       False
DEWP       False
RAIN       False
wd          True
WSPM       False
station    False
dtype: bool

In [36]:
dataset.describe()

No          year         month           day          hour  \
count  35064.000000  35064.000000  35064.000000  35064.000000  35064.000000   
mean   17532.500000   2014.662560      6.522930     15.729637     11.500000   
std    10122.249256      1.177213      3.448752      8.800218      6.922285   
min        1.000000   2013.000000      1.000000      1.000000      0.000000   
25%     8766.750000   2014.000000      4.000000      8.000000      5.750000   
50%    17532.500000   2015.000000      7.000000     16.000000     11.500000   
75%    26298.250000   2016.000000     10.000000     23.000000     17.250000   
max    35064.000000   2017.000000     12.000000     31.000000     23.000000   

                PM2          PM10           SO2           NO2            CO  \
count  35064.000000  35064.000000  35064.000000  35064.000000  35064.000000   
mean      82.120075    109.588187     17.152554     59.121859   1244.561887   
std       81.142233     94.299574     22.557057     36.586135   1192.758674   
min        3.000000      2.000000      0.285600      2.000000    100.000000   
25%       23.000000     39.000000      3.000000     31.000000    500.000000   
50%       58.000000     87.000000      9.000000     53.000000    900.000000   
75%      112.000000    153.000000     21.000000     81.000000   1500.000000   
max      898.000000    984.000000    341.000000    290.000000  10000.000000   

                 O3          TEMP          PRES          DEWP          RAIN  \
count  35064.000000  35064.000000  35064.000000  35064.000000  35064.000000   
mean      55.649690     13.585130   1011.846665      3.123449      0.067383   
std       56.563751     11.395866     10.401084     13.685001      0.909798   
min        0.214200    -16.800000    985.900000    -35.300000      0.000000   
25%        9.000000      3.100000   1003.300000     -8.100000      0.000000   
50%       42.000000     14.500000   1011.400000      3.800000      0.000000   
75%       80.000000     23.300000   1020.100000     15.600000      0.000000   
max      423.000000     40.500000   1042.000000     28.500000     72.500000   

               WSPM  
count  35064.000000  
mean       1.708373  
std        1.203846  
min        0.000000  
25%        0.900000  
50%        1.400000  
75%        2.200000  
max       11.200000

In [62]:
dataset.columns

Index(['No', 'year', 'month', 'day', 'hour', 'PM2', 'PM10', 'SO2', 'NO2', 'CO',
       'O3', 'TEMP', 'PRES', 'DEWP', 'RAIN', 'wd', 'WSPM', 'station'],
      dtype='object')

In [63]:
 X =  dataset[['year', 'month', 'day', 'hour','PM10',   'SO2', 'NO2', 'CO',
       'O3', 'TEMP', 'PRES', 'DEWP', 'RAIN', 'WSPM']]
X

year  month  day  hour  PM10   SO2   NO2     CO    O3  TEMP    PRES  \
0      2013      3    1     0   4.0   4.0   7.0  300.0  77.0  -0.7  1023.0   
1      2013      3    1     1   8.0   4.0   7.0  300.0  77.0  -1.1  1023.2   
2      2013      3    1     2   7.0   5.0  10.0  300.0  73.0  -1.1  1023.5   
3      2013      3    1     3   6.0  11.0  11.0  300.0  72.0  -1.4  1024.5   
4      2013      3    1     4   3.0  12.0  12.0  300.0  72.0  -2.0  1025.2   
...     ...    ...  ...   ...   ...   ...   ...    ...   ...   ...     ...   
35059  2017      2   28    19  29.0   5.0  35.0  400.0  95.0  12.5  1013.5   
35060  2017      2   28    20  37.0   7.0  45.0  500.0  81.0  11.6  1013.6   
35061  2017      2   28    21  37.0  10.0  66.0  700.0  58.0  10.8  1014.2   
35062  2017      2   28    22  44.0  12.0  87.0  700.0  35.0  10.5  1014.4   
35063  2017      2   28    23  31.0  10.0  79.0  600.0  42.0   8.6  1014.1   

       DEWP  RAIN  WSPM  
0     -18.8   0.0   4.4  
1     -18.2   0.0   4.7  
2     -18.2   0.0   5.6  
3     -19.4   0.0   3.1  
4     -19.5   0.0   2.0  
...     ...   ...   ...  
35059 -16.2   0.0   2.4  
35060 -15.1   0.0   0.9  
35061 -13.3   0.0   1.1  
35062 -12.9   0.0   1.2  
35063 -15.9   0.0   1.3  

[35064 rows x 14 columns]

In [64]:
Y = dataset[['PM2']]
Y

PM2
0       4.0
1       8.0
2       7.0
3       6.0
4       3.0
...     ...
35059  12.0
35060  13.0
35061  16.0
35062  21.0
35063  19.0

[35064 rows x 1 columns]

In [69]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3 )


In [75]:
scaler = preprocessing.StandardScaler().fit(x_train)


In [76]:
X_train_scaled = scaler.transform(x_train)


In [77]:
X_train_scaled.mean(axis=0)

array([ 3.34989171e-14,  1.79488468e-17, -3.32922159e-17,  6.25314663e-17,
        1.29115898e-16, -4.84908361e-17,  6.33999589e-17, -8.07698107e-17,
       -1.84699424e-16, -1.78040980e-17, -2.49373172e-15,  3.50292010e-17,
        6.65844317e-18,  6.91899095e-17])

In [78]:
X_train_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
X_test_scaled = scaler.transform(x_test)


In [81]:
X_test_scaled.mean(axis=0)

array([ 0.00945544, -0.0085761 ,  0.00627174, -0.0028894 , -0.00955536,
       -0.00695809, -0.00365093, -0.01013698,  0.00568425,  0.00953304,
       -0.00778473,  0.00945246,  0.00610221, -0.00674875])

In [82]:
X_test_scaled.std(axis=0)

array([1.0038473 , 0.99347134, 1.00165381, 1.00638865, 0.97471957,
       0.9946619 , 0.9981359 , 0.99444779, 1.00821617, 0.99517517,
       0.99691057, 0.99828481, 0.92997274, 0.97984876])

In [83]:
pipeline = make_pipeline(preprocessing.StandardScaler(), 
                         RandomForestRegressor(n_estimators=100))

In [84]:
pipeline.get_params()

{'memory': None,
 'steps': [('standardscaler', StandardScaler()),
  ('randomforestregressor', RandomForestRegressor())],
 'verbose': False,
 'standardscaler': StandardScaler(),
 'randomforestregressor': RandomForestRegressor(),
 'standardscaler__copy': True,
 'standardscaler__with_mean': True,
 'standardscaler__with_std': True,
 'randomforestregressor__bootstrap': True,
 'randomforestregressor__ccp_alpha': 0.0,
 'randomforestregressor__criterion': 'mse',
 'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 'auto',
 'randomforestregressor__max_leaf_nodes': None,
 'randomforestregressor__max_samples': None,
 'randomforestregressor__min_impurity_decrease': 0.0,
 'randomforestregressor__min_impurity_split': None,
 'randomforestregressor__min_samples_leaf': 1,
 'randomforestregressor__min_samples_split': 2,
 'randomforestregressor__min_weight_fraction_leaf': 0.0,
 'randomforestregressor__n_estimators': 100,
 'randomforestregressor__n_jobs': None,
 'randomforest

In [85]:
hyperparameters = { 'randomforestregressor__max_features' : ['auto', 'sqrt', 'log2'],
                  'randomforestregressor__max_depth': [None, 5, 3, 1]}

In [109]:
clf = GridSearchCV(pipeline, hyperparameters, cv=10)
 
clf.fit(x_train, y_train)


C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Plea

C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Plea

C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Plea

C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)
C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Plea

C:\Users\FLORA\anaconda3\lib\site-packages\sklearn\pipeline.py:335: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self._final_estimator.fit(Xt, y, **fit_params_last_step)


GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('standardscaler', StandardScaler()),
                                       ('randomforestregressor',
                                        RandomForestRegressor())]),
             param_grid={'randomforestregressor__max_depth': [None, 5, 3, 1],
                         'randomforestregressor__max_features': ['auto', 'sqrt',
                                                                 'log2']})